const homeStyles = {
    container: {
      backgroundColor: '#111',
      color: 'white',
      padding: 20,
      minHeight: '100vh',
      fontFamily: 'sans-serif',
    },
    header: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    title: {
      fontSize: '28px',
      fontWeight: 'bold',
    },
    addButton: {
      backgroundColor: 'cyan',
      border: 'none',
      padding: '10px 20px',
      borderRadius: '50px',
      color: '#111',
      fontWeight: 'bold',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
    },
    userList: {
      display: 'flex',
      flexDirection: 'column',
      gap: '12px',
    },
    userCard: {
      display: 'flex',
      alignItems: 'center',
      padding: 10,
      borderRadius: 8,
      border: '1px solid #ccc',
      transition: '0.3s',
    },
    avatar: {
      width: 40,
      height: 40,
      borderRadius: '50%',
      marginRight: 10,
      objectFit: 'cover',
    },
    userInfo: {
      flexGrow: 1,
    },
    editButton: {
      background: 'transparent',
      border: 'none',
      color: 'cyan',
      fontSize: 18,
      cursor: 'pointer',
      marginRight: 10,
    },
    deleteButton: {
      background: 'transparent',
      border: 'none',
      color: 'red',
      fontSize: 18,
      cursor: 'pointer',
    },
    popupOverlay: {
      position: 'fixed',
      top: 0, left: 0, right: 0, bottom: 0,
      background: 'rgba(0, 0, 0, 0.7)',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 999,
    },
    popupBox: {
      background: '#222',
      padding: 20,
      borderRadius: 10,
      width: 300,
      boxShadow: '0 2px 10px rgba(0,0,0,0.5)',
      color: 'white',
    },
    popupTitle: {
        fontSize: '24px',
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 20,
    },

    popupActionsCentered: {
        display: 'flex',
        justifyContent: 'center',
        gap: 15,
        marginTop: 15,
    },

    cancelButtonCustom: {
        padding: '8px 16px',
        backgroundColor: 'transparent',
        border: '2px solid cyan',
        borderRadius: 5,
        color: 'cyan',
        fontWeight: 'bold',
        cursor: 'pointer',
    },

    input: {
        width: '100%',
        marginBottom: 10,
        padding: 10,
        background: 'transparent',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: 'white',
        borderRadius: 5,
        color: 'white',
        outline: 'none', 
        transition: 'border-color 0.3s, box-shadow 0.3s',
    },
    inputFocus: {
        borderColor: 'cyan',
        boxShadow: '0 0 5px cyan',
    },
    popupActions: {
      display: 'flex',
      justifyContent: 'flex-end',
      gap: 10,
    },
    submitButton: {
      padding: '8px 16px',
      backgroundColor: 'cyan',
      border: 'none',
      borderRadius: 5,
      color: '#111',
      fontWeight: 'bold',
      cursor: 'pointer',
    },
    cancelButton: {
      padding: '8px 16px',
      backgroundColor: 'gray',
      border: 'none',
      borderRadius: 5,
      color: 'white',
      cursor: 'pointer',
    },
  };
  
  export default homeStyles;
  